package entities;
// Generated Nov 14, 2015 7:59:56 PM by Hibernate Tools 3.6.0



/**
 * ComingSoonCourse generated by hbm2java
 */
public class ComingSoonCourse  implements java.io.Serializable {


     private int id;
     private Courses courses;

    public ComingSoonCourse() {
    }

	
    public ComingSoonCourse(int id) {
        this.id = id;
    }
    public ComingSoonCourse(int id, Courses courses) {
       this.id = id;
       this.courses = courses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }




}


