package entities;
// Generated Nov 23, 2015 7:01:02 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import model.DB_Lessons;

/**
 * Courses generated by hbm2java
 */
public class Courses implements java.io.Serializable {

	private Integer id;
	private Teachers teachers;
	private String title;
	private Date startDate;
	private String info;
	private Integer fee;
	private String image;
	private Set comingSoonCourses = new HashSet(0);
	private Set lessonses = new HashSet(0);
	private Set enrolledStudentses = new HashSet(0);
	private Set popCourses = new HashSet(0);

	public Courses() {
	}
	public int getNumberOfLesson(){
		int res=0;
		List<Lessons> lesson=DB_Lessons.getAllLessons();
		for (int i = 0; i < lesson.size(); i++) {
			if(lesson.get(i).getCourses().getId().equals(id)){
				res++;
			}
		}
		
		return res;
	}
	public Courses(Teachers teachers, String title) {
		this.teachers = teachers;
		this.title = title;
	}

	public Courses(Teachers teachers, String title, Date startDate, String info, Integer fee, String image,
			Set comingSoonCourses, Set lessonses, Set enrolledStudentses, Set popCourses) {
		this.teachers = teachers;
		this.title = title;
		this.startDate = startDate;
		this.info = info;
		this.fee = fee;
		this.image = image;
		this.comingSoonCourses = comingSoonCourses;
		this.lessonses = lessonses;
		this.enrolledStudentses = enrolledStudentses;
		this.popCourses = popCourses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Teachers getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Teachers teachers) {
		this.teachers = teachers;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public Integer getFee() {
		return this.fee;
	}

	public void setFee(Integer fee) {
		this.fee = fee;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Set getComingSoonCourses() {
		return this.comingSoonCourses;
	}

	public void setComingSoonCourses(Set comingSoonCourses) {
		this.comingSoonCourses = comingSoonCourses;
	}

	public Set getLessonses() {
		return this.lessonses;
	}

	public void setLessonses(Set lessonses) {
		this.lessonses = lessonses;
	}

	public Set getEnrolledStudentses() {
		return this.enrolledStudentses;
	}

	public void setEnrolledStudentses(Set enrolledStudentses) {
		this.enrolledStudentses = enrolledStudentses;
	}

	public Set getPopCourses() {
		return this.popCourses;
	}

	public void setPopCourses(Set popCourses) {
		this.popCourses = popCourses;
	}

}
