package entities;
// Generated Nov 14, 2015 7:59:56 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Courses generated by hbm2java
 */
public class Courses implements java.io.Serializable {

	private Integer id;
	private Teachers teachers;
	private String title;
	private Date startDate;
	private String info;
	private Integer fee;
	private Set lessonses = new HashSet(0);
	private Set popCourses = new HashSet(0);
	private Set enrolledStudentses = new HashSet(0);
	private Set comingSoonCourses = new HashSet(0);
	String url;

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Courses() {
	}

	public Courses(Teachers teachers, String title) {
		this.teachers = teachers;
		this.title = title;
	}

	public Courses(Teachers teachers, String title, Date startDate, String info, Integer fee, Set lessonses,
			Set popCourses, Set enrolledStudentses, Set comingSoonCourses) {
		this.teachers = teachers;
		this.title = title;
		this.startDate = startDate;
		this.info = info;
		this.fee = fee;
		this.lessonses = lessonses;
		this.popCourses = popCourses;
		this.enrolledStudentses = enrolledStudentses;
		this.comingSoonCourses = comingSoonCourses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Teachers getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Teachers teachers) {
		this.teachers = teachers;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public Integer getFee() {
		return this.fee;
	}

	public void setFee(Integer fee) {
		this.fee = fee;
	}

	public Set getLessonses() {
		return this.lessonses;
	}

	public void setLessonses(Set lessonses) {
		this.lessonses = lessonses;
	}

	public Set getPopCourses() {
		return this.popCourses;
	}

	public void setPopCourses(Set popCourses) {
		this.popCourses = popCourses;
	}

	public Set getEnrolledStudentses() {
		return this.enrolledStudentses;
	}

	public void setEnrolledStudentses(Set enrolledStudentses) {
		this.enrolledStudentses = enrolledStudentses;
	}

	public Set getComingSoonCourses() {
		return this.comingSoonCourses;
	}

	public void setComingSoonCourses(Set comingSoonCourses) {
		this.comingSoonCourses = comingSoonCourses;
	}
}
