package entities;
// Generated Nov 14, 2015 7:59:56 PM by Hibernate Tools 3.6.0



/**
 * EnrolledStudents generated by hbm2java
 */
public class EnrolledStudents  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private Courses courses;

    public EnrolledStudents() {
    }

    public EnrolledStudents(Users users, Courses courses) {
       this.users = users;
       this.courses = courses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }




}


