package entities;
// Generated Nov 18, 2015 9:24:44 PM by Hibernate Tools 4.3.1



/**
 * EnrolledStudents generated by hbm2java
 */
public class EnrolledStudents  implements java.io.Serializable {


     private Integer id;
     private Courses courses;
     private Users users;

    public EnrolledStudents() {
    }

    public EnrolledStudents(Courses courses, Users users) {
       this.courses = courses;
       this.users = users;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


