package entities;
// Generated Nov 19, 2015 6:31:32 PM by Hibernate Tools 4.3.1



/**
 * Lessons generated by hbm2java
 */
public class Lessons  implements java.io.Serializable {


     private Integer id;
     private Courses courses;
     private Integer order;
     private String title;
     private String info;
     private String video;

    public Lessons() {
    }

	
    public Lessons(Courses courses, String title) {
        this.courses = courses;
        this.title = title;
    }
    public Lessons(Courses courses, Integer order, String title, String info, String video) {
       this.courses = courses;
       this.order = order;
       this.title = title;
       this.info = info;
       this.video = video;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }
    public Integer getOrder() {
        return this.order;
    }
    
    public void setOrder(Integer order) {
        this.order = order;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public String getVideo() {
        return this.video;
    }
    
    public void setVideo(String video) {
        this.video = video;
    }




}


